[package]
name = "bolt-rs"
version = "0.1.0"
authors = ["Matt 961 <matt961@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "0.2.0-alpha.6"
bytes = "^0.4"
